name: ferry_flutter
version: 0.9.0-dev.2
homepage: https://ferrygraphql.com/
description: Flutter widgets for the Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
topics:
  - graphql
  - gql
  - ferry
dependencies:
  ferry:
    path: ../../packages/ferry
  gql_exec: '>=0.4.0 <2.0.0'
  ferry_exec:
    path: ../../packages/ferry_exec
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.2
  pedantic: ^1.11.0
